### ISSUE TITLE
Default to include data/ files?

### ISSUE THREAD

**Issue by tseemann** [andrewjpage/plasmidpredictor#1]
I note that `data/` has the files downloaded.
It would be great if it could default to use those.
Are they part of the pip `resources` section?

eg.
```
parser.add_argument('--output_prefix',	 '-o', help='Output directory', 
   default =   pkg_resources.get_distribution("plasmidpredictor").the_files_we_need)
```

I guess the reason is ethical/political 

Could make everyone cite Plasmidfinder as well as your future JOSS paper.

**Comment by tseemann** [comment]
I guess the reason is ethical/political 

Could make everyone cite Plasmidfinder as well as your future JOSS paper.

**Comment by andrewjpage** [comment]
I've bundled the database and included it by default if you dont provide a database. I've also added the plasmidfinder paper citation to the readme and updated the location to point to their bitbucket version instead of the old zip.
