### ISSUE TITLE
plasmidpredictor_database_downloader shouldn't download surprisingly

### ISSUE THREAD

**Issue by tseemann** [andrewjpage/plasmidpredictor#6]
```
% plasmidpredictor_database_downloader
Downloading data with:
curl -X POST --data "folder=plasmidfinder&filename=plasmidfinder.zip"
```

Noooo! whats going on. whats all this scrolling. whats happened??

I think `--outdir` should be required ... "principle of LEAST SURPRISE".

Most people expect to see `--help` to stderr when no parameter supplied.

**Comment by andrewjpage** [comment]
Fixed
