### ISSUE TITLE
Consider homopolymer compressed kmers

### ISSUE THREAD

**Issue by tseemann** [andrewjpage/plasmidpredictor#7]
Heng uses homo-compressed k-mers in minimap2
Might be useful here
Or not

**Comment by tseemann** [comment]
Can transform the data with  `$dna =~ s/(.)\1*/\1/g`   :)

**Comment by tseemann** [comment]
In case you need it:

https://github.com/tseemann/dehomopolymerate

```
dehomopolymerate -l 15 < in.fq.gz > out.fq
```

**Comment by andrewjpage** [comment]
Thanks a million!

**Comment by andrewjpage** [comment]
Added as an option
